version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
    - 3.8.0
  - dependency-name: com.github.gmazzo:okhttp-mock
    versions:
    - 1.3.2
    - 1.4.0
  - dependency-name: org.json:json
    versions:
    - "20201115"
  - dependency-name: com.squareup.okhttp3:okhttp
    versions:
    - 4.9.0
